---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2025.4.0
    env:
      TZ: "Europe/Berlin"
    envFrom:
      - secretRef:
          name: home-assistant-secrets
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "192.168.128.161"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: false
        ingressClassName: "nginx"
        hosts:
          - host: "hass.homelab"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.homelab"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
      usb1:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB1
      config:
        enabled: true
        existingClaim: nfs-data-pvc
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-conbee", operator: In, values: ["true"]}
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.98.2
        #git:
        #  deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: false
        service:
          type: LoadBalancer
          externalIPs:
            - "192.168.128.172"
          externalTrafficPolicy: Local
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 1500Mi
