---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: banzaicloud-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://kubernetes-charts.banzaicloud.com
  timeout: 3m
