---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/cilium/charts
  timeout: 3m
