---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://charts.crossplane.io/stable
  timeout: 3m
