---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgres-operator-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/zalando/postgres-operator/tree/master/charts
  timeout: 3m
