apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: temporal
  namespace: flux-system
spec:
  interval: 360m
  timeout: 300s
  url: https://github.com/temporalio/helm-charts.git
  ref:
    branch: master
