---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal-operator-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://alexandrevilain.github.io/temporal-operator
  timeout: 3m
