---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: pi-hole-charts
        namespace: flux-system
      interval: 5m
  values:
    dnsmasq:
      customDnsEntries:
        - address=/hass-config.homelab/192.168.128.160
        - address=/nextcloud/192.168.128.163
    persistentVolumeClaim:
      enabled: true
    serviceWeb:
      loadBalancerIP: 192.168.128.173
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.128.174
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
