---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.23.0
      sourceRef:
        kind: HelmRepository
        name: pi-hole-charts
        namespace: flux-system
      interval: 5m
  values:
    maxUnavailable: 0
    antiaff:
      enabled: true
      strict: false
    replicaCount: 1
    data:
      storageClass: nfs-client
    image:
      repository: pihole/pihole
      tag: 2024.03.2
    dnsmasq:
      customDnsEntries:
        - address=/hass/192.168.128.161
        - address=/hass-config/192.168.128.172
        - address=/nextcloud/192.168.128.163
        - address=/pihole/192.168.128.174
        - address=/vernemq/192.168.128.171
        - address=/deconz/192.168.128.165
    persistentVolumeClaim:
      enabled: false
    monitoring:
      sidecar:
        enabled: true
    podAnnotations:
      prometheus.io/port: '9617'
      prometheus.io/scrape: 'true'
    serviceWeb:
      loadBalancerIP: 192.168.128.173
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.128.174
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
