---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm
      chart: nextcloud
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: 23.0.3-apache
    nextcloud:
      host: "nc.tretau.dev"
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: NEXTCLOUD_ADMIN_USER
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
      internalDatabase:
        enabled: false
      externalDatabase:
        enabled: true
        type: postgresql
        host: nextcloud-pg-cluster
        user: nextcloud
        database: nextcloud
        existingSecret:
          enabled: true
          secretName: nextcloud-user.nextcloud-pg-cluster.credentials.postgresql.acid.zalan.do
          usernameKey: username
          usernamePassword: password
      configs:
        proxies.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' =>
              array (
                0 => '192.168.128.163',
                1 => 'nextcloud.kube.home',
                2 => 'nc.tretau.dev',
              ),
          );
      resources:
        limits:
          cpu: 23m
          memory: 283Mi
        requests:
          cpu: 23m
          memory: 283Mi
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/hsts: "true"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;

          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      hosts:
      - host: nc.tretau.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "nc.tretau.dev"
    persistence:
      enabled: true
      storageClass: nfs-client
    metrics:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.128.163
