apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: default
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:7yc4pmRw,iv:Jd9tbNXdQM31u/Hm0zJRkeAB7cIuH4W5QW6D/UZfU90=,tag:1FPwqwL8CSmlVhlHMqzWjA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:EgccT70KHxZPStPGjSe1bXfLGdIMds5tqw==,iv:zEGuFlFPZM+xAS7ozhwXBrhlBon+aaND85mtLW0O4Jo=,tag:sMn4x8dfw4F/wX04gxDG8Q==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:4wk9OLZP,iv:5oYlE2+HnRj/WDOtuslUAWUX38PupXbg8GaA73rGXP0=,tag:aSLvJnMXg7T7sqmIWfYNBg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:EQoQOTpgUYr4zWKbsxkKC5UAcok4OMUvmg==,iv:uZHjqGTOx1+1rXwNWy8IiWNN7b9I7x9dYOWik6rDBPU=,tag:9dHXiW+cf/+6SkF8torI6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-30T08:40:40Z"
    mac: ENC[AES256_GCM,data:IB8NsIAZrk1p3A6hP40w2X3f07Kl5ugDCEClavonTygBgJbR/b6goioxci0wwbN9V2uGTAAsq+IDvZgtMKx8dAmokqMeCtdY1qfVuq5aOKZAFAVdcnqGxIEt+Bigg3WaNbKU5W/ajIGQ7SNOJ/bRsWSRzzATO5SMtoCIJDIj8Cs=,iv:GPR1Bq8vV+CjgB6oNEo/+COB8+NkI3eY3uuIQD4rvNk=,tag:8EXSZjXwGTuBcmVs6Qkq0A==,type:str]
    pgp:
        - created_at: "2021-06-30T08:40:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+YbdLFRVIrpARAAkyZfiLuzmYLaWAo6P//6dNa0txFU5vjrKkv5pp1JqKNg
            9isa/UrU8vQ3Cw7bIW14j15FCGa6aBSnC0C2Ymsy6mNx39WJtz1dgxC5kil6XC4o
            qp71FlOFulVSQ9Ba81RLBUenDNAAXRfDMwm4i/1cvxStdaQbL9VsCALjWem8wnVf
            uX2SgcrpzNzBtWH3DXocNweZCRyNbifKkgmIlfCgLdnqI3wbAw1m/V8NJpwSppy1
            LaUzPjgPfOi1mX5+o1I3xVkCh5/GMxy2CCrp5Gilbj00Ygw/gkLrCKtSuADsD+DW
            cULs0Wz0ViRhj+eebQpC59zXqeFONytr5gyTfCsh0jFnJ7XimzhW+R3YltibgK+7
            S+VYHJHMYBzxatJVQ/U2WNEtOry2gAj3yQilXkjX0SbY7kztfWMTH4eV2JFXnyuu
            9IsfKlQOEOJtZwYk+57+yH8Hz6RqEODDLui7e6ZpqXIrM9U21Ol3buBsX/rKHWxR
            D89F1rk/H7cLCgWWrNL4ZsNgPtVSk91cj/sGolTRkHGha86omBZAqw1QDqtPkf5U
            uQ3ZSI35P40CvSIMeyjfkFa2SvD7NDKtiSNFxZsnocIhQvCZZqsYP2WqwIzjcPdT
            GcYV+zdOsrH+lN/A8pwJhqeM/Rt4MYu4z+e61YbWvoOiXnxXFouBXm+xzMtF9WXU
            aAEJAhVtYp7/y1RPID7AxPDjSTWV8jPFALF//UaF3ukASEhUX2N71F8f2f4vfiCf
            mIIF5uC9jI5SUBfw2cjkJvdieE6O0PpYGE7gnYlbZIX4a/yQX2ZtZfU9KSfJjyuF
            quoEKFkC8BIL
            =x4Ql
            -----END PGP MESSAGE-----
          fp: 9FE48B0532014F896AEA06271FD0C8B4A0F81C16
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
