apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secrets
    namespace: kube-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:s1OOpTzjigAcdtYdX/M=,iv:tdluXFcdV0rwoqYmIt+G/uv18DP+vZtiHHKRYdgvquA=,tag:p8WNvG2N7SgOwaF/rU4BRw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ze/XAzvhy6iiAg==,iv:pXZrxRN/rcBgDnGlrD7QZva+A/f05gRD6IgR8eKVOAM=,tag:agG8IqkOR64IMWW22+tj0w==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:gJkcvRFdMNqNHJSw0tlCCsn0FLDFkJyYjeXtYWfCAKfIrJV6hWX2fg==,iv:5/eGPywrKPW1nteif3k2QnjLfz8KxrxsF8xbe/+h1uY=,tag:A838QjXCkVnCfL0Hnj+aaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-24T08:53:57Z"
    mac: ENC[AES256_GCM,data:wR9eOu/i2S+AMb5FhHWqr1BYHy3jm2UOwMSFerMUn6RXLyekBv96TAvJxm3PR3eFK5up3OFOi9RR4yPQ36eECuV+eNCr63w9OiM0h/kD8xMmQKfqj14D1GLbw8fb/hEQ+R5msRD+Klr9mRz5u0++oU6YgUWlm+Jgc2IgRA8SEAk=,iv:XvnYfyzucAHvrOVxRu2HtkthJXJIFUCR6sGI3PIWd4M=,tag:hvu0jSx+MeNDgX+4xkmR5Q==,type:str]
    pgp:
        - created_at: "2022-01-24T08:53:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+YbdLFRVIrpARAAhpjBbGMSR3epKornkBmSh3C5H3iBqUpscIRRtGKaIWcN
            5GVldpNWflzoMEhnVmwSjJVM9EgpMoFOf+7jZV9UpUBvhxMU944nwB638M9B4czq
            tQW+CKsdtmIbkdBdMI0A3OThbdRr1xhbfopOI8t2XNb+7H2jU0yBnVe8jXBDTpCm
            scmiRJL/FX7pA3lusbW0JKxmYjP3YuzXW82V3JFAIJ2OC6wLd1fIfrt1LUQfQ9vF
            dPPdBJrqn3WNEBJ/1gt9TLud1KOY/ADFHSoCtDSE2wj+Wfykf86uEp0NRI8wDrRR
            TW2Vu0/PUjhvOQmVRYoLD8goK2ZZEEPoqtI43jJCAXl0qra1RbEGGz4G30xoVi6+
            S6hQnqo+7Kr8wUIH4gFDenP+lBUP4O6Cd2GgEuJGCWWKFIyB0IgokiAHuUQ7l1zR
            sXnmSVm6GP7hFJOP9QKZli5m4y0D6TQHPaz9fQuBc7DQqJRmtJe9oA11IpFZ3G7k
            YyKv6gqlLDZiJyoS6zwaSN39uHp6EX0YmNpotOUrnxLa8ZvVvAZ/v2dGBUN5W4Nd
            HVLDVvblRcVmjJBSCqHh7lAyDJ+XRfSkfwOExDZwu78K1xl1UT0vOElsbiOTuXOg
            ZAnmbmqrAhYNrtLWSlosxqQhcyGpfgQfyzatqy4MFkqmSxS/WFc0oGwAYByIHGrU
            ZgEJAhDMqxGUeUhQKtN6ZqiB79v0/Q4NryixHNqSuIItQb9v3JrWR8ShJuc2oeMg
            3UsSPxc73pgjTMQje6brPQDbpHQ48YIvVZnNLLkM2AH6lzAYr7zSK1dMNrAhEOmN
            8TcCXvLRCg==
            =8T8E
            -----END PGP MESSAGE-----
          fp: 9FE48B0532014F896AEA06271FD0C8B4A0F81C16
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
