---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "torben.tretau@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: "bam@tretau.net"
          apiTokenSecretRef:
            name: cert-manager-secrets
            key: CLOUDFLARE_TOKEN
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: kube-system
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - tretau.dev
    - '*.tretau.dev'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-t0n
  namespace: apps
spec:
  secretName: acme-crt-t0n-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - t0n.eu
    - '*.t0n.eu'