---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/ttretau/homelab-gitops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-default
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-extra
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./flux-system-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-kube-system
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-monitoring
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Enable decryption
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/operator
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-operator
      namespace: istio-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/system
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/gateway
  prune: true
  validation: client