---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: v1.14.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
  values:
    connect:
      serviceType: ClusterIP
      api:
        serviceMonitor:
          enabled: true
