---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ccsm
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: zeebe-cloud-events-router
      version: 0.0.51
      sourceRef:
        kind: HelmRepository
        name: camunda-zeebe-legacy-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        cpu: 100m
        memory: 450Mi
      limits:
        cpu: 300m
        memory: 850Mi