apiVersion: v1
kind: ConfigMap
metadata:
  name: connectors-application-config
  namespace: default
data:
  application.properties: |
    #empty
  application.yaml: |
    server:
      port: 8080
    zeebe:
      client:
        broker:
          gateway-address: localhost:26500
        security:
          plaintext: true
        worker:
          max-jobs-active: 32
          threads: 10
    operate:
      client:
        enabled: false
    camunda:
      operate:
        enabled: false
      connector:
        polling:
          enabled: false
