---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zeebe
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.camunda.io
      chart: camunda-platform
      version: 8.2.12
      sourceRef:
        kind: HelmRepository
        name: camunda-zeebe-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      identity:
        auth:
          enabled: false
    keycloak:
      enabled: false
    tasklist:
      enabled: false
    optimize:
      enabled: false
    elasticsearch:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: 1000Mi
          cpu: 100m
        limits:
          cpu: 500m
          memory: 1500Mi
    webModeler:
      enabled: false
    identity:
      enabled: false
    operate:
      enabled: false
    zeebe-gateway:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 450Mi
        limits:
          cpu: 300m
          memory: 450Mi
    zeebe:
      clusterSize: 1
      partitionCount: 1
      replicationFactor: 1
      gateway:
        replicas: 1
      resources:
        requests:
          memory: 1000Mi
          cpu: 100m
        limits:
          cpu: 500m
          memory: 1500Mi
