---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: apps
  labels:
    app: code-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: code-server
