---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-solis-s3-logger
  namespace: apps
  labels:
    app: py-solis-s3-logger
spec:
  selector:
    matchLabels:
      app: py-solis-s3-logger
  template:
    metadata:
      labels:
        app: py-solis-s3-logger
    spec:
      containers:
        - name: py-solis-s3-logger
          image: ghcr.io/ttretau/py-solis-s3-logger:main
          imagePullPolicy: Always
          env:
            - name: SOLIS_LOGGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: py-solis-s3-logger
                  key: solis-password
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi