---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 4.9.14
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "influxdb"
      tag: "1.8.5"
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 50Gi
      storageClass: nfs-client
    resources:
      requests:
        memory: 1000Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    config:
      opentsdb:
        enabled: true
      graphite:
        enabled: true
        database: graphitedb
        retention-policy: ""
        bind-address: ":2003"
        protocol: tcp
        consistency-lvel: one
        templates:
        - "*.app env.service.resource.measurement"
        - "servers.* .host.resource.measurement.field*"
#    podAnnotations:
#      backup.velero.io/backup-volumes: influxdb-data
#    tolerations:
#    - key: "arm"
#      operator: "Exists"
