---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.128.168
    persistence:
      enabled: true
      size: 50Gi
      existingClaim: nfs-monitoring-pvc
    resources:
      requests:
        memory: 1000Mi
        cpu: 100m
      limits:
        memory: 1500Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10