---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: istio-operator
      version: 0.0.91
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-charts
        namespace: flux-system
      interval: 5m
  values:

