---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alarm-monitor-fast
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: alarm-monitor-fast
        property: key
