---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apps
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: ALARM_MONITOR_ALLOWED_HOSTS
      remoteRef:
        key: apps-secrets
        property: ALARM_MONITOR_ALLOWED_HOSTS
    - secretKey: ALARM_MONITOR_DATABASE_URL
      remoteRef:
        key: apps-secrets
        property: ALARM_MONITOR_DATABASE_URL
    - secretKey: ALARM_MONITOR_SECRET_KEY
      remoteRef:
        key: apps-secrets
        property: ALARM_MONITOR_SECRET_KEY
