---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: SECRET_EMAIL
      remoteRef:
        key: cert-manager-secrets
        property: SECRET_EMAIL
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: cert-manager-secrets
        property: SECRET_DOMAIN
    - secretKey: CLOUDFLARE_TOKEN
      remoteRef:
        key: cert-manager-secrets
        property: CLOUDFLARE_TOKEN