---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: default-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: SECRET_EMAIL
      remoteRef:
        key: default-secrets
        property: SECRET_EMAIL
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: default-secrets
        property: SECRET_DOMAIN
    - secretKey: SECRET_MINIO_ACCESS_KEY
      remoteRef:
        key: default-secrets
        property: SECRET_MINIO_ACCESS_KEY
    - secretKey: SECRET_MINIO_SECRET_KEY
      remoteRef:
        key: default-secrets
        property: SECRET_MINIO_SECRET_KEY