---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: HASS_API_PASSWORD
      remoteRef:
        key: home-assistant-secrets
        property: HASS_API_PASSWORD
    - secretKey: HASS_CONFIG_USERNAME
      remoteRef:
        key: home-assistant-secrets
        property: HASS_CONFIG_USERNAME
    - secretKey: HASS_CONFIG_PASSWORD
      remoteRef:
        key: home-assistant-secrets
        property: HASS_CONFIG_PASSWORD
    - secretKey: HASS_TOKEN
      remoteRef:
        key: home-assistant-secrets
        property: HASS_TOKEN
    - secretKey: HASS_MQTT_PASSWORD
      remoteRef:
        key: home-assistant-secrets
        property: HASS_MQTT_PASSWORD
    - secretKey: HASS_MQTT_USERNAME
      remoteRef:
        key: home-assistant-secrets
        property: HASS_MQTT_USERNAME