---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: SECRET_EMAIL
      remoteRef:
        key: monitoring-secrets
        property: SECRET_EMAIL
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: monitoring-secrets
        property: SECRET_DOMAIN
    - secretKey: SECRET_GRAFANA_PASSWORD
      remoteRef:
        key: monitoring-secrets
        property: SECRET_GRAFANA_PASSWORD
    - secretKey: SECRET_GRAFANA_USER
      remoteRef:
        key: monitoring-secrets
        property: SECRET_GRAFANA_USER
    - secretKey: SECRET_MINIO_ACCESS_KEY
      remoteRef:
        key: monitoring-secrets
        property: SECRET_MINIO_ACCESS_KEY
    - secretKey: SECRET_MINIO_SECRET_KEY
      remoteRef:
        key: monitoring-secrets
        property: SECRET_MINIO_SECRET_KEY
    - secretKey: SECRET_ALERT_MANAGER_SLACK_WEBHOOK
      remoteRef:
        key: monitoring-secrets
        property: SECRET_ALERT_MANAGER_SLACK_WEBHOOK