---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: NEXTCLOUD_ADMIN_PASSWORD
      remoteRef:
        key: nextcloud
        property: NEXTCLOUD_ADMIN_PASSWORD
    - secretKey: NEXTCLOUD_ADMIN_USER
      remoteRef:
        key: nextcloud
        property: NEXTCLOUD_ADMIN_USER
    - secretKey: nextcloud-password
      remoteRef:
        key: nextcloud
        property: nextcloud-password
    - secretKey: nextcloud-username
      remoteRef:
        key: nextcloud
        property: nextcloud-username