---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: py-solis-s3-logger
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: py-solis-s3-logger
        property: username
    - secretKey: solis-password
      remoteRef:
        key: py-solis-s3-logger
        property: solis-password