---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: prod
  target:
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: slack-url
        property: address
