apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: prod
  namespace: temporal
spec:
  version: 1.23.0
  numHistoryShards: 1
  persistence:
    defaultStore:
      sql:
        user: temporal
        pluginName: postgres12
        databaseName: temporal
        connectAddr: temporal-pg-cluster.temporal.svc.cluster.local:5432
        connectProtocol: tcp
      skipCreate: true
      tls:
        enabled: true
        enableHostVerification: false
      passwordSecretRef:
        name: temporal.temporal-pg-cluster.credentials.postgresql.acid.zalan.do
        key: password
    visibilityStore:
      sql:
        user: temporal
        pluginName: postgres12
        databaseName: temporal_visibility
        connectAddr: temporal-pg-cluster.temporal.svc.cluster.local:5432
        connectProtocol: tcp
      skipCreate: true
      tls:
        enabled: true
        enableHostVerification: false
      passwordSecretRef:
        name: temporal.temporal-pg-cluster.credentials.postgresql.acid.zalan.do
        key: password
#  log:
#    level: debug
  ui:
    enabled: true
  admintools:
    enabled: false
  # metrics:
  #   enabled: true
  #   prometheus:
  #     listenPort: 9090
  #     scrapeConfig:
  #       serviceMonitor:
  #         enabled: true
  #         labels:
  #           release: test
  #         metricRelabelings:
  #         - sourceLabels: [__name__]
  #           targetLabel: __name__
  #           replacement: temporal_$1
#  dynamicConfig:
#    pollInterval: 10s
#    values:
#      matching.numTaskqueueReadPartitions:
#        - value: 5
#          constraints: {}
#      matching.numTaskqueueWritePartitions:
#        - value: 5
#          constraints: {}
