---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: temporal-operator
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: temporal-operator-charts
        namespace: flux-system
  values:
    {}
