apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: temporal-pg-cluster
  namespace: apps
spec:
  teamId: "temporal"
  volume:
    storageClass: nfs-client
    size: 2Gi
  numberOfInstances: 1
  users:
    temporal:  # database owner
      - superuser
      - createdb
    temporal_user: []  # role for application foo
  databases:
    temporal: temporal  # dbname: owner
  preparedDatabases:
    temporal_visibility:
      defaultUsers: true
      schemas:
        temporal_visibility: { }
    temporal:
      defaultUsers: true
      schemas:
        temporal: { }
  postgresql:
    version: "13"
