apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: inventar
  namespace: prod
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventar
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 120
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: inventar
  service:
    # container port
    port: 8765
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  analysis:
    # schedule interval (default 60s)
    interval: 10s
    # max number of failed metric checks before rollback
    threshold: 15
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    metrics:
      - name: starlette_request_duration_seconds
        thresholdRange:
          max: 15
        interval: 30s
