apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  namespace: default
spec:
  storageClassName: nfs-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.128.56
    path: "/mnt/storage/data"
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class
  resources:
    requests:
      storage: 1Gi
