apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
  labels:
    app: nfs-prometheus-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.128.56
    path: "/mnt/storage/prometheus"
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime