apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets-repo
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.9.18
  url: https://github.com/external-secrets/external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 24h
  path: ./deploy/crds/
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets-repo
