---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 60m
  chart:
    spec:
      chart: external-secrets
      version: v0.9.18
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
  values:
    certController:
      create: false
    webhook:
      create: false
    installCRDs: false
