---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: prod
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.kube-system.svc.cluster.local
      vaults:
        k8s: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: kube-system