---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tetragon
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  values: