---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tetragon
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  values:
    tetragon:
      enabled: false
      prometheus:
        metricsLabelFilter: "namespace,workload,binary" # "pod" label is disabled
