apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argo
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: 5.19.3
      sourceRef:
        kind: HelmRepository
        name: argo-charts
        namespace: flux-system
      interval: 5m
values:
  server:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.128.174