apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argo
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: 5.19.3
      sourceRef:
        kind: HelmRepository
        name: argo-charts
        namespace: flux-system
      interval: 5m
values:
  global:
    image:
      repository: ghcr.io/flux-subsystem-argo/fsa/argocd
      tag: v2.5.7-fl.3-main-b0b6148f
  server:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.128.174