---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vzlogger
  namespace: apps
  labels:
    app: vzlogger
spec:
  selector:
    matchLabels:
      app: vzlogger
  template:
    metadata:
      labels:
        app: vzlogger
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 18
        fsGroup: 18
      containers:
        - name: vzlogger
          image: ghcr.io/ttretau/vzlogger:master
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/usb-ir-lesekopf0
              name: usb-ir-lesekopf0
            - mountPath: "/etc/vzlogger.conf"
              subPath: vzlogger.conf
              name: vzlogger-configmap-volume
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: vzlogger-configmap-volume
          configMap:
            name: vzlogger
        - name: usb-ir-lesekopf0
          hostPath:
            path: /dev/usb-ir-lesekopf0
