---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vzlogger
  namespace: apps
  labels:
    app: vzlogger
spec:
  selector:
    matchLabels:
      app: vzlogger
  template:
    metadata:
      labels:
        app: vzlogger
    spec:
      securityContext:
#        runAsUser: 100
        runAsUser: 0
        runAsGroup: 18
        fsGroup: 18
      containers:
        - name: vzlogger
          image: public.ecr.aws/bitnami/python:3.8
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["sleep", "30000"]
#          command: ["ls", "-n", "/dev/ttyUSB1"]
#          command: ["getent", "passwd"]
          volumeMounts:
            - mountPath: /dev/ttyUSB1
              name: ttyusb1
            - mountPath: /src
              name: host-volume
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: host-volume
          hostPath:
            path: /tmp
            type: Directory
        - name: ttyusb1
          hostPath:
            path: /dev/ttyUSB1
