apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: az-default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-account-creds
      key: credentials
