apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.crossplane.io/stable
      chart: crossplane
      version: 1.11.2
      sourceRef:
        kind: HelmRepository
        name: crossplane-charts
        namespace: flux-system
      interval: 5m
  values:
    provider:
      packages:
        - xpkg.upbound.io/crossplane-contrib/provider-aws:v0.37.1
        - xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1
        - xpkg.upbound.io/crossplane-contrib/provider-helm:v0.13.0
        - xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.6.0
