apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nextcloud-pg-cluster
  namespace: default
spec:
  teamId: "nextcloud"
  volume:
    storageClass: nfs-client
    size: 2Gi
  numberOfInstances: 1
  users:
    nextcloud:  # database owner
    - superuser
    - createdb
    nextcloud_user: []  # role for application foo
  databases:
    nextcloud: nextcloud  # dbname: owner
  postgresql:
    version: "13"
