apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nextcloud-minimal-cluster
  namespace: default
spec:
  teamId: "nextcloud"
  serviceAnnotations:
    enableMasterLoadBalancer: true
  volume:
    storageClass: nfs-client
    size: 1Gi
  numberOfInstances: 1
  users:
    nextcloud:  # database owner
    - superuser
    - createdb
    nextcloud_user: []  # role for application foo
  databases:
    nextcloud: nextcloud  # dbname: owner
  preparedDatabases:
    nextcloud: {}
  postgresql:
    version: "13"