---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui/
      chart: postgres-operator-ui
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator-ui-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: LoadBalancer
      externalIPs:
        - "192.168.128.172"
      externalTrafficPolicy: Local
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
