---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://github.com/zalando/postgres-operator/tree/master/charts
      chart:
      version: 1.6.3
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: default
      interval: 5m
  values:
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
