---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
      chart: postgres-operator
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 150m
        memory: 250Mi
