---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://storage.googleapis.com/t3n-helm-charts
      chart: mosquitto
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: t3n-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eclipse-mosquitto
      tag: 1.6.12
    replicaCount: 1
    monitoring:
      sidecar:
        enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.128.171
    persistence:
      enabled: false
