apiVersion: v1
kind: Secret
metadata:
    name: apps-secrets
    namespace: apps
stringData:
    ALARM_MONITOR_DATABASE_URL: ENC[AES256_GCM,data:D8Ztk5TzDf7T8xcliSNq0DecSa87J31ICVbnV/wTHkY7InX38iSwlk83yl8AJhQ9Kwae5477Rtd2qSS4BeOB1gVsy6fFP65zYxvr+VjGNavGYFGqddVdixmcnP0zuQ52iYu2oZLStBzEFbmgHHYReFncA7csfKL5FRD8YTWlimzLKQzBN53MV/5mSBEgPMA2Xs4ZIR2Typ+zdAfHt7JdCN4zDI+cowieuJMROGSuga1l5lrfXJIjIh55gP5pPXNXObve,iv:VJLwLKu7ErOeC1GPxM+f0g/R5PQDCT3I7r0r4NzBayw=,tag:KTReryQeDjgLB8EKguB2ZQ==,type:str]
    ALARM_MONITOR_SECRET_KEY: ENC[AES256_GCM,data:e1C+YjAm8SwFF04u/jxgVTigSMFMXr9/MmrywJRWxsnc2ud9J2b7Y5/WLqZqjOlT,iv:MePtBoy3ulvp1DCqmVHmohtAEY2OlA0jVg9p2TsipbY=,tag:OHKUOD+DjhZYos6rNEZLow==,type:str]
    ALARM_MONITOR_ALLOWED_HOSTS: ENC[AES256_GCM,data:xmUrz7APtYzAw+Mh,iv:zUYtVyWsGLKsaeF3aKLkm3FInwTBA6AGy0XUp5/JHo8=,tag:+wCKmC1ynjRe5MKci9Ow5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-26T18:26:21Z"
    mac: ENC[AES256_GCM,data:aNRSN1CW5UR7KVEJbZCwuNVjQMOmSVEEINfsy/zOUHSqmAw5lzHB/28zbmLwZI8jakVGK+WWyxbGayV1vkTIXd7u3lmaTNCcKz3wdPH7RIURW0rAJ6CYHg7oxHndV+cCPAq4rKxNkux6QFgM4dQIUOTO9X4K3F81KCNE0OrqAgo=,iv:v9mu1PK1MitanJCWkoP9zeoBxfSLYirfbqez0HGqLCY=,tag:Sgzf122BhCFAwiugIIwzJQ==,type:str]
    pgp:
        - created_at: "2022-01-26T18:26:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+YbdLFRVIrpAQ/7BhCfjUEpkuMoG6s2Z9AJUXEGOMP80X90BFq6i4R00EEh
            jJwb15m020mtCMgMRcIrNWoc6gjUdIPBltLQpW4IDWvq1x05hkdhuFDD6oYLJToy
            KDB1FfLoS3/SQ9cCSNNM6TxhlKhdXGLI1dg1XmU8zMoJdDHx8zxEx9JC6lr//die
            NPm2RbRsSBBT+8ng2HzzEkkQCQHt+1lO0VP7A6BnqgR3l6Wmc0Ffki7LcHxazP/6
            Ogx/WWj/TpMfNBqbXRrA93m0rekIhUTMdIjrTuxzSKk8TX91dfbV9GekpRwtjmMm
            Wz2U5NtPG9IFcT3PUdKhv+xixlVGgFpruPz3pNqvLV8ECaDRgOAN+qC1X49xaSU6
            8BM7ZN/Poao8rMv6WQCBwIXc4NI0/aKrRyGdadccfV9nudDK/yIFqbFP0cCRHKKS
            //y5wTpOmF1oRkY+Qx0XDKGGZsMj9R2XV6deDJixb8j4WrbUPbw/FHfA7ym9DiyV
            lg+NJejCNh04lWJQAMwRhRnnythpURFAQmuReV/UJYBIPSqyX8NcNTO9anYtmCtb
            VXpmZKegpDs33OPQpWOX15qXbeJ7E27oFckOrsXdien8Wu3PUNNM0VkkI/eM7M8E
            Uaj3D+y2Y17yueMsGwQESJ+XwZQczMFHR99ZOTwfx3GQA6FTWYbMlCv91CzaEkPU
            aAEJAhDIdRA84rfVjwfNB42wOcM76thxfmAnMJLMCU7wzY9XlVm/4x43l2hP0Hq+
            EiUWfF6UwzLWnJkRL6re2tPYmw386wL5xiiSsyVkiCcMelZFHnsY4DOrDLs037xR
            rRnugztJwocW
            =uAP3
            -----END PGP MESSAGE-----
          fp: 9FE48B0532014F896AEA06271FD0C8B4A0F81C16
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
