apiVersion: v1
kind: Secret
metadata:
    name: apps-secrets
    namespace: apps
stringData:
    ALARM_MONITOR_DATABASE_URL: ENC[AES256_GCM,data:6Cvzaj9+pwVLXcKp2IoQ/bz0ipLSzRqm3CRdfTTCwL2m97n4smQL6hTEdUANDILq1ylwNdlcgnq+4Eg7gQ2yvXIepy1uBUKqXGeDdOcTWoTryFje7M8DQFBqw3+AsvYw0/cFJ0DkkA2lQzOepvbXy6G+v+ouv7rukbgMjDmYuD/y/e5v0g89Q9ztRIOXINcmle8e+xVKhjDBRVi7gck/aKiA0qNA2EPmtcvBGxZ1i+dELy5nFzh4LWD3CvHsM5UT1oQ6,iv:0Gro5kiJW9aWmT6nd15pwr+1Xcf7JE2LVBq7e6pNhak=,tag:DcsAugPE0ioNqcpbECQ1qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-20T08:13:54Z"
    mac: ENC[AES256_GCM,data:x9LFdzG4EcG5ve/0PhTY3axqrHyVAoRjV479F6Q0HTokAsxYohuEbyfNwnuSWOw4oNh/OXyJKesaOzW798+LIaPKZRg7KdLRfnFyT53gzi9XtLdpYQfi5fm6sg5KPicgQKsmUkwbwIXIwzlNgqBjrQ+xV0k8hpwiq3G6cMajTn4=,iv:wELRGJpeXQpl60YW1rvCs2/T6xsnTL/CHoaG2WQw9h4=,tag:PgggcP4BekyPakaktmW2Wg==,type:str]
    pgp:
        - created_at: "2022-01-20T08:13:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+YbdLFRVIrpAQ//XhUhYr/B82sVfuafdJBcd/jr6pfxdOOXRq6jAotbFrIv
            13FMOg1RewL655L1TH7WILsG6tER0OVFE4Q8i7VBzsXte5+TGBG74Pe8PI/zT8QN
            H0bIFkTniFu2i7r6P8DdeeHoP7Df453yjmH22YQ+NvZ2Q2Bp1+FAb0hSkT7pnSz3
            yqci1upBPl35YHoavJptaMD6W0v+c8hA+XT7NfaBfgFmA8AyzPgOC2gRwpxWODJr
            kxyQld7FeWjoFK8fOD6gtjZ6qrED4e3xlO5c+V+TpK4h9X7e3Xz2w5zETUignLBL
            kdmVE7KzmgDucGreE0ifmY9LiyZUEguqBxJcwnE9zeorUC24ew3elxp7Dt99LIou
            mzaDJ9zr9jBI/7OweKgRkKNYOAfioD12q7qgbIN7qL5+kjiGL9Gg5WKHsyaYKCzw
            fQnPJRyF4re+wk+SZpFkjoaASISijnzKXKyUONUBoRdoKya77HnDqmvaZMMOPwwv
            WH5FcmdGDZBJRgkOfOGKXUDzEG8FGIGsmnXyZ4/k7v/oTcuRaGJHarMtQQa9lTkQ
            3dCGI1TLEQ+i1erhGXb5E9211WxTLr8VZ2WGexVzPFredxEM4nHEnOgpEI+5788T
            AQebQ0ZlwMgNtqAPcSqEA51jSEuLyBRiQoDlXEdll7aP+jCyuUMA0wtgMLu2rvnU
            aAEJAhCOcB8Dj6xzmUVJEZ6jEJjNZXHUdUoweUtkESojpGRDG22v3fUnY8oClFY3
            hcEH1KyzkAREwl+wekTCZugeBXnb4Kls17ReKekW40R4w/W85jsBVca6zPEqS3vH
            jUrmFXLVpd/I
            =99qb
            -----END PGP MESSAGE-----
          fp: 9FE48B0532014F896AEA06271FD0C8B4A0F81C16
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
