---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 8.0.10
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-08-08T04-50-06Z
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-08-08T02-33-58Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    persistence:
      existingClaim: "nfs-data-pvc"
      subPath: "minio"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
#      hosts: [minio.eviljungle.com]
#      tls:
#      - hosts:
#        - minio.eviljungle.com
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 1
  valuesFrom:
    - kind: Secret
      name: default-secrets
      valuesKey: SECRET_MINIO_ACCESS_KEY
      targetPath: accessKey
    - kind: Secret
      name: default-secrets
      valuesKey: SECRET_MINIO_SECRET_KEY
      targetPath: secretKey
