---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-monitor-backend
  namespace: apps
  labels:
    app: alarm-monitor-backend
spec:
#  minReadySeconds: 5
#  revisionHistoryLimit: 5
#  progressDeadlineSeconds: 60
#  strategy:
#    rollingUpdate:
#      maxUnavailable: 0
#    type: RollingUpdate
  selector:
    matchLabels:
      app: alarm-monitor-backend
  template:
    metadata:
#      annotations:
#        prometheus.io/scrape: "true"
      labels:
        app: alarm-monitor-backend
    spec:
      containers:
        - name: alarm-monitor-worker
          image: ghcr.io/ttretau/alarm_monitor:main
          command:
            - python
            - run_worker.py
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "False"
            - name: TEMPORAL_HOST
              value: "temporal-frontend.apps.svc.cluster.local"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        - name: alarm-monitor-backend
          image: ghcr.io/ttretau/alarm_monitor:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8765
              name: http
              protocol: TCP
#          volumeMounts:
#            - mountPath: "/home/app/web/cfg"
#              name: root-crt
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: ALARM_MONITOR_DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: ALARM_MONITOR_SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: ALARM_MONITOR_ALLOWED_HOSTS
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: alarm-monitor-fast
                  key: key
            - name: DEBUG
              value: "False"
            - name: TEMPORAL_HOST
              value: "temporal-frontend.apps.svc.cluster.local"
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: 8765
#            initialDelaySeconds: 20
#            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
#      volumes:
#      - name: root-crt
#        secret:
#          secretName: apps-secrets
#          items:
#            - key: ALARM_MONITOR_ROOT_CRT
#              path: ".postgresql/root.crt"
