apiVersion: v1
kind: Service
metadata:
  name: alarm-monitor-service
  namespace: apps
spec:
  selector:
    app: alarm-monitor-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8765