---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 2
      config:
        hsts: true
        hsts-include-subdomains: true
        hsts-max-age: "31449600"
      use-forwarded-headers: "true"
      service:
        loadBalancerIP: 192.168.128.160
        externalTrafficPolicy: Local
      ingressClassResource:
        default: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "kube-system/acme-crt-secret"
      resources:
        requests:
          memory: 300Mi
          cpu: 25m
        limits:
          memory: 400Mi
