apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi