---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: deconz
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: deconz
      version: 6.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: deconzcommunity/deconz
      tag: "2.24.0"
    timezone: "Europe/Berlin"
    ingress:
      main:
        enabled: false
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "192.168.128.165"
        externalTrafficPolicy: Local
    securityContext:
      privileged:  true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-conbee", operator: In, values: ["true"]}
    persistence:
      config:
        enabled: true
        existingClaim: nfs-data-pvc
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
        mountPath: /dev/ttyACM0
    env:
      DECONZ_DEVICE: /dev/ttyACM0
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        custom: true
        spec:
          failureThreshold: 80
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 10
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 35m
        memory: 512Mi
    monitoring:
      enabled: true
