---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 4.1.12
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    crds:
      enabled: true
#    configInline:
#      address-pools:
#        - name: default
#          protocol: layer2
#          addresses:
#            - 192.168.128.160-192.168.128.179
#    prometheusRule:
#      enabled: true
#    prometheus:
#      enabled: true
#      serviceMonitor:
#        enabled: true
#      prometheusRule:
#        enabled: true
